parameters:
    regions: CoreBundle\Entity\Region
    city: CoreBundle\Entity\City
    organize: CoreBundle\Entity\Organize
    forum: CoreBundle\Entity\Forum
    forum_post: CoreBundle\Entity\ForumPost
    photo: CoreBundle\Entity\Photo
    news: CoreBundle\Entity\News
    partner: CoreBundle\Entity\Partner
    voting: CoreBundle\Entity\Voting
    voting_params: CoreBundle\Entity\VotingParams

services:
    forum_post.handler:
         class: CoreBundle\Handler\ForumPostHandler
         arguments: [@service_container, %forum_post%]

    region.handler:
        class: CoreBundle\Handler\RegionHandler
        arguments: [@service_container, %regions%]

    news.handler:
        class: CoreBundle\Handler\NewsHandler
        arguments: [@service_container, %news%]

    city.handler:
        class: CoreBundle\Handler\CityHandler
        arguments: [@service_container, %city%]

    partner.handler:
        class: CoreBundle\Handler\PartnerHandler
        arguments: [@service_container, %partner%]

    organize.handler:
        class: CoreBundle\Handler\OrganizeHandler
        arguments: [@service_container, %organize%]

    admin.partner:
        class: CoreBundle\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-diamond "></i>', group: "Партнеры", label: "Партнеры" }
        arguments:
            - ~
            - %partner%
            - 'SonataAdminBundle:CRUD'

    admin.region:
        class: CoreBundle\Admin\RegionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-globe"></i>', group: "Местоположения", label: "Регионы" }
        arguments:
            - ~
            - %regions%
            - 'SonataAdminBundle:CRUD'

    admin.city:
        class: CoreBundle\Admin\CityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-globe"></i>', group: "Местоположения", label: "Города" }
        arguments:
            - ~
            - %city%
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [CoreBundle]]

    admin.organize:
        class: CoreBundle\Admin\OrganizeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-globe"></i>', group: "Местоположения", label: "Организации" }
        arguments:
            - ~
            - %organize%
            - 'SonataAdminBundle:CRUD'

    admin.forum:
        class: CoreBundle\Admin\ForumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-list-ul"></i>', group: "Форум", label: "Форумы" }
        arguments:
            - ~
            - %forum%
            - 'SonataAdminBundle:CRUD'
            - @service_container

    admin.forum.post:
        class: CoreBundle\Admin\ForumPostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-list-ul"></i>', group: "Форум", label: "Посты", show_in_dashboard: false }
        arguments:
            - ~
            - %forum_post%
            - 'SonataAdminBundle:CRUD'
            - @service_container

    admin.voting:
        class: CoreBundle\Admin\VotingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-list-ul"></i>', group: "Форум", label: "Голосование" } #, show_in_dashboard: false }
        arguments:
            - ~
            - %voting%
            - 'SonataAdminBundle:CRUD'

    admin.voting_params:
        class: CoreBundle\Admin\VotingParamsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-list-ul"></i>', group: "Форум", label: "Параметры голосования" } #, show_in_dashboard: false }
        arguments:
            - ~
            - %voting_params%
            - 'SonataAdminBundle:CRUD'

    admin.news:
        class: CoreBundle\Admin\NewsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm,  icon: '<i class="fa fa-newspaper-o"></i>', group: "Новости", label: "Новости" }
        arguments:
            - ~
            - %news%
            - 'SonataAdminBundle:CRUD'