core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

web:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
