# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    pdo:
        class: PDO
        arguments:
            dsn: "mysql:host=%database_host%;dbname=%database_name%"
            user: %database_user%
            password: %database_password%
        calls:
            - [ setAttribute, [3, 2] ] # \PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: [@pdo, {lock_mode: 0}]

    session.handler.pdolifetime:
            class:     App\CoreBundle\Session\Storage\Handler\PdoSessionLifetimeHandler
            arguments: [@service_container, @pdo, {lock_mode: 0}]
            
    
